CREATE TABLE IF NOT EXISTS alerts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  entity VARCHAR(128) NOT NULL,
  external_id VARCHAR(32) NOT NULL,
  source VARCHAR(16) NOT NULL,
  device VARCHAR(16),
  owner VARCHAR(16),
  team VARCHAR(16),
  tags VARCHAR(128),
  start_time BIGINT NOT NULL,
  agg_id INT,
  auto_expire BOOLEAN NOT NULL,
  auto_clear BOOLEAN NOT NULL,
  is_aggregate BOOLEAN NOT NULL,
  expire_after INT,
  severity SMALLINT NOT NULL,
  status SMALLINT NOT NULL,
  metadata JSON,
  last_active BIGINT NOT NULL,
  scope VARCHAR(16));

CREATE TABLE IF NOT EXISTS suppression_rules (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  alert_name VARCHAR(64),
  device VARCHAR(16),
  entity VARCHAR(64),
  site VARCHAR(16),
  region VARCHAR(16),
  created_at BIGINT NOT NULL,
  duration INT NOT NULL,
  reason varchar(128) NOT NULL,
  creator varchar(64) NOT NULL);
